{% set name = "scramp" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d27d768408c6fc025a0e567eed84325b0aaf24364c81ea5974e8334ae3c4fda3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >3.5
    - pip
  run:
    - python >3.5
    - asn1crypto ==1.4.0

test:
  imports:
    - scramp

about:
  home: https://github.com/tlocke/scramp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A pure-Python implementation of the SCRAM authentication protocol
  description: |
    A Python implementation of the SCRAM authentication protocol defined by
    RFC 5802 and RFC 7677.

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
