travis:
  secure:
    BINSTAR_TOKEN: YH+QkzZDxsD6iELXSjltTMX3NIcVInSl2oRnIAwLalMcCBaNPhVUJ+ZJyiLimZ98ITgP8fXu1MqafYwod2OSpE/dTmaL+El70VezIfzBcX/jBmzerq101FqFciSybSY0d4WgKEnry/I29fmulEX/5oU0fpEu96sN9vnE0l7RA9xM85yE3EuJj/C9Ad3UhC+vWfJ7ztf7ujVPYhDOf6SV2gdSquXYErwJ1CuZqdzE1BtsSt0zN8yDsj38s5BITWlMOps6HuKKSaKSUUaslmyNpM50UzhCWOjUGZ4T0OdU0tk8EZwdKiyyD96Bnf0UOeJ6Sstf4vGfujszztpv6cXPcmaqh5orRCwUeWg+REvmDaRu+nl9Fxnl0eLYeSBsK/8M2kVbu+f6lUpEH53VFpeacwan2w+mDe73x0TCP5V1ymROnMWCRYtjio6lfi2wsKzd1HXb8CZZGjCWlIS1owVIi9Zv4qOZgK7miTuQ9Q+yA08kg3KQuSxGWA5t9ncQ9Zl8fOBqZSJEfe8kljSBCt1xV54iVjmyOryAfgyMyF2XHnKQRIG8o4DEIE4/x7FX7pwgUNf9xhiZPChzX5H/g9qRBtzTEWDIAfEOxx7+b/hGUMvJulh6zgmddUKrFTDGqL6ZLLlBe1sjAGyKK71UrFb7WBSraCniEOldDJ3l+wqEqFI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
